backend:
  name: git-gateway
  branch: main # Branche où les articles sont stockés

media_folder: "public/images/uploads" # Dossier pour les images
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Articles de blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
